---
title: 'Wrangling Data from microplate OD600 growth curve in 96WP'
author: "El Park"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
geometry: margin=2.54cm
---


```{r, include=FALSE} 

#Setup
source("C:/Users/parke/OneDrive - Indiana University/GitHub/RSetup.R")

```

Load and wrangle data
```{r}
#load data, change date
data<-read.csv("../data/20250521OD600.csv")
design<-read.csv("../reference/20250521OD600Design.csv", header=FALSE)

source("C:/Users/parke/OneDrive - Indiana University/GitHub/ASG-fitness-effects/microplate_fitness_assay/datawrangling_code/Functions/wrangle96WP_med.str.inf.R")

```

Prep Data
```{r}
#FEP, Fitness Effects of Phage (subtract Ctrl Infection avgs from corr Strain/Media rows)
# ctrl avgs from od.long
ctrl_avg <- od.long %>%
  filter(Infection == "ctrl") %>%  # Keep only control rows
  group_by(Media, Strain) %>%
  summarize(ctrl_avg = mean(total.OD, na.rm = TRUE), .groups = "drop")
# subtract control average
FEP <- od.long %>%
  left_join(ctrl_avg, by = c("Media", "Strain")) %>%
  mutate(total.OD = ctrl_avg - total.OD) %>%
  select(-ctrl_avg)  # Remove temporary column
FEP<-FEP%>%  #Fitness effects of Phage
  filter(!grepl("ctrl", Infection))


#FES, Fitness effects of Strain (subtract avg WT values from each corr Media/Infection rows)
# wt avgs from od.long
WTavg <- od.long %>%
  filter(Strain == "WT") %>%  # Keep only control rows
  group_by(Media, Infection) %>%
  summarize(WTavg = mean(total.OD, na.rm = TRUE), .groups = "drop")
# subtract control average
FES <- od.long %>%
  left_join(WTavg, by = c("Media", "Infection")) %>%
  mutate(total.OD = total.OD - WTavg) %>%
  select(-WTavg)  # Remove temporary column
FES<-FES%>%  #Fitness effects of Phage
  filter(!grepl("WT", Strain))


#FEP6, Fitness Effects of Phage in 1st 6 hours
#Isolate 6h post-infection
OD.long6<-OD.long[(1:7008),]
OD.long6 <- OD.long6 %>%
  group_by(Well, Media, Strain, Infection) %>%
  summarize(total.OD = sum(OD600, na.rm = TRUE), .groups = "drop")
# ctrl avgs from OD.long6
ctrl_avg6 <- OD.long6 %>%
  filter(Infection == "ctrl") %>%  # Keep only control rows
  group_by(Media, Strain) %>%
  summarize(ctrl_avg6 = mean(total.OD, na.rm = TRUE), .groups = "drop")
# subtract control average
FEP6 <- OD.long6 %>%
  left_join(ctrl_avg6, by = c("Media", "Strain")) %>%
  mutate(total.OD = ctrl_avg6 - total.OD) %>%
  select(-ctrl_avg6)  # Remove temporary column
FEP6<-FEP6%>%  #Fitness effects of Phage
  filter(!grepl("ctrl", Infection))

```

Analysis
```{r}
#Infection vs no infection
FEPa <- aov(total.OD ~  Strain * Infection , data = FEP)
summary(FEPa)

#Mutant vs WT
FESa <- aov(total.OD ~  Strain * Infection , data = FES)
summary(FESa)

#Infection vs no infection just 6 hr
FEP6a <- aov(total.OD ~  Strain * Infection , data = FEP6)
summary(FEP6a)


```

